language: node_js
node_js:
- '0.10'
- '0.11'
script:
- npm run build
- npm run coveralls
before_script:
- git config --global user.email "daisuketaniwaki@gmail.com"
- git config --global user.name "Travis-CI"
after_script:
- git remote add origin git@github.com:dtaniwaki/node-custom-console.git
- git checkout $TRAVIS_BRANCH
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git commit lib -m 'Compile the coffee script'
- git config push.default simple
- git push origin $TRAVIS_BRANCH
env:
  global:
    secure: GJg5Eehu60kF9VSO8c+SuJkkBZ6P+h+HjD6XnLT/v6wFkCjxkIV8YG7ukUzDzZKlpUi6QeK+qItgMx8dUxJCRL8sIOxQkPPNF/8Pq/T99AnWZRFjLllUTBVXIiM4ub88H22AxCcMWDyIkex0enzYohIuZ6keug+ze2MTGrYnAR4=
